manateelazycat/aweshell

aweshell.el

If you set aliases by script,
Eshell load each on of them as write alias file
on startup.
That slows down startup significantly.
What do you think?

Remove handy aliases

---

README.md
aweshell.el
eshell-up.el

>Emacs package for quickly navigating to a specific parent directory in eshell without having to repeatedly typing cd `..`.
[origional package](https://github.com/peterwvj/eshell-up)
I like it for it saves a lot of typing.

Add eshell-up package

---

README.md
aweshell.el

This PR doesn't change any default behavior.
Add variable `aweshell-use-exec-path-from-shell`, defaults to `t`.
`exec-path-from-shell` is pretty slow, and I have my path configured elsewhere.

Make exec-path-from-shell optional

---

aweshell.el

Previously the toggle command doesn't return to normal buffer when there are multiple aweshell buffers.
Now it's fixed.

Fix toggle

---

aweshell.el

When:
1. executing a file in current dir
2. execute a file, type enter and starts interacting with the program
1. fix the delimiter: added \n\t etc
2. add nonsticky property so the face doesn't follow

Fix edge cases for command validation

---

aweshell.el

Sometimes I will use elisp fuction as a command in eshell, this commit can help check the command you typed  whether is a legal elisp function or not.
BTW, in my windows system I found that the function `aweshell-validate-command` cannot detect the
`cd` command. it will show the `cd` is an illegal command because i don't have `cd.exe` explicitly in my
`$PATH` environment variables, it's strange that because `cd` should be a built-in command of eshell.
this commit will also fix it (by recognizing `cd` as a elisp function)

Add support of checking elisp functions to `aweshell-validate-command' 

---

aweshell.el

when you use prefix arg.
It tries to reuse existing aweshell buffers,
if none found, it creates a new one with current directory.

Now aweshell-toggle can open eshell in current directory

---

aweshell.el

1 instead of nil is passed to arg when there is no prefix argument,
making my code invalid when there is no prefix argument.
Now it is fixed
Sorry, I don't know prefix argument passes 1 instead of nil.

Handle prefix argument correctly

---

esh-autosuggest.el

This mode doesn't use company as front end.
Now I can use company for shell completions.
Additionally, enabling this mode turns esh-autosuggest-mode off.

Add esh-autosuggest-companyless-mode

---

aweshell.el

Sorry for the formatting/spacing changes and You do not have to merge this if you do no like it. Following is the code that fixes above issue:
```
(cl-search "\*" prefix)
(cl-search "\\" prefix)
```
I also updated the change log and doc string.

Fix company munu error when cmd has * or \

---

aweshell.el

Replace 'esh-parse-shell-history' with 'aweshell-parse-shell-history', it looks like 'esh-parse-shell-history' has been deleted.

bugfix: replace 'esh-parse-shell-history'

---

README.md
aweshell.el

Switch to another aweshell buffer.
Preselect the closest aweshell to the `default-directory' of the current buffer

feature: add `aweshell-switch-buffer'

---

aweshell.el

instead of (getenv "SHELL")
AFAIK, shell-command use shell-file-name.

infer shell by `shell-file-name`

---

aweshell.el

fix(aweshell-validate-command): beginning-of-line conflict with eshell-prompt-regexp

---

aweshell.el

#46  will cause new bug，since no restrictions of prompt existing. The correct way is replace (beginning-of-line) with function skipping  field boundary.

fix(aweshell-validate-command): replace (beginning-of-line) with (forward-line 0)

---

aweshell.el

In #47 I was so stupid to forget function `(line-end-position)` which can't get position across the field boundary too. I din't find alternative  one [here](https://www.gnu.org/software/emacs/manual/html_node/elisp/Text-Lines.html), so i use local variable instead.

fix(aweshell-validate-command): (line-end-position) can't move across field boundary

---

aweshell.el

Otherwise, eshell output filters (or, well, something) raises an error when inserting text with the read-only property. With this change, `cat my-image.png` works.
Note: This could be something particular to my setup, I'm not sure. All I know is that with this, `cat some-image.png` works and without it, it doesn't.

fix(cat): remove the read-only property before inserting

---

aweshell.el

It maybe work better when you split window vertically, then call  `aweshell-dedicated-toggle`.

use side-window to pop dedicated-window

---

aweshell.el

I fixed the bug I made. Now, the `aweshell-dedicated-window-height` is work. 
I'm sooooo sorry T_T.

fix the bug that aweshell-dedicated-window-height can't work.

---

aweshell.el

Hi,
This PR allows the use of completion frameworks different than `ido` when running `aweshell-search-history` while keeping backwards compatibility for `ido` users.
E.g: following snippet allows completion with `ivy`.
```elisp
(setq aweshell-search-history-completing-read-fn 'completing-read)
```
Thanks!

Parameterize completing-read function used on search-history
